app/form_cabinet/models.py
from .. import db

class Contacts(db.Model):
	__tablename__ = "contacts"

	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(15), unique=False, nullable=True)
	email = db.Column(db.String(40), unique=False, nullable=True)
	phone = db.Column(db.String(15), unique=False, nullable=True)
	subject = db.Column(db.String(15), unique=False, nullable=True)
	message = db.Column(db.Text, unique=False, nullable=True)

	def __repr__(self):
		return f"Name : {self.name}, Email: {self.email}"

app/form_cabinet/__init__.py
from flask import Blueprint

form_bp = Blueprint('form', __name__, template_folder='templates/form_cabinet')
from . import views

app/form_cabinet/views.py
import logging
from flask import  render_template, request, redirect, session, url_for, flash

from app.account.form import ContactForm
from .. import db
from .models import Contacts
from . import form_bp

@form_bp.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    main = logging.getLogger('main')
    main.setLevel(logging.DEBUG)
    handler = logging.FileHandler('log')
    format = logging.Formatter('%(asctime)s  %(name)s %(levelname)s: %(message)s')
    handler.setFormatter(format)
    if form.validate_on_submit():
        session['username'] = form.name.data
        session['email'] = form.email.data
        save_to_db(form)
        flash("Data sent successfully: " + session.get('username') + ' ' + session.get('email'), category = 'success')
        return redirect(url_for("form.contact"))

    elif request.method == 'POST':
        flash("Validation failed", category = 'warning')
        main.addHandler(handler)
        main.error(form.name.data + " " + form.email.data + " " + form.phone.data + " " + form.subject.data + " " + form.message.data)

    if(session.get('username') == None):
        return render_template('contact.html', form=form, username="Guest")
    else :
        form.name.data = session.get('username')
        form.email.data = session.get('email')
        return render_template('contact.html', form=form, username=session.get('username'))

@form_bp.route('/database')
def database() :
    contacts = Contacts.query.all()
    return render_template('database.html', contacts=contacts)

@form_bp.route('/database/delete/<id>')
def delete_by_id(id):
    data = Contacts.query.get(id)
    db.session.delete(data)
    db.session.commit()
    return redirect(url_for("form.database"))


def save_to_db(form) :
    contact = Contacts(
        name = form.name.data,
        email = form.email.data,
        phone = form.phone.data,
        subject = form.subject.data,
        message = form.message.data
    )
    try:
        db.session.add(contact)
        db.session.commit()
    except:
        db.session.flush()
        db.session.rollback()

app/form_cabinet/templates/form_cabinet/contact.html
{% extends "layout.html" %}


{% block content %}

{% from "_render_field.html" import render_field %}

<div class="col-6 mx-auto">

	<div class="card">

		<div class="card-header">
			<h5>Form</h5>
		</div>

		<div class="card-body">
			<form method="post">
				{{ form.csrf_token }}
				{{ render_field(form.name, class="form-control") }}
				{{ render_field(form.email, class="form-control") }}
				{{ render_field(form.phone, class="form-control") }}
				{{ render_field(form.subject, class="form-control") }}
				{{ render_field(form.message, class="form-control") }}
				{{ form.submit(class="btn btn-primary") }}
			</form>
		</div>

	</div>

</div>

{% endblock %}

app/form_cabinet/templates/form_cabinet/database.html
{% extends 'layout.html' %}

{% block content %}
<table class="table">
	<thead class="table-light table-bordered">
		<tr>
			<th scope="col">Id</th>
			<th scope="col">Name</th>
			<th scope="col">Email</th>
			<th scope="col">Phone</th>
			<th scope="col">Subject</th>
			<th scope="col">Message</th>
			<th scope="col">Delete</th>
		</tr>
	</thead>
	{% for data in contacts %}
	<tbody>
		<thead class="table-primary table-bordered">
			<tr>
				<td>{{data.id}}</td>
				<td>{{data.name}}</td>
				<td>{{data.email}}</td>
				<td>{{data.phone}}</td>
				<td>{{data.subject}}</td>
				<td>{{data.message}}</td>
				<td><a href="{{ url_for('form.delete_by_id', id=data.id) }}" type="button"
						class="btn btn-danger">Delete</a>
				</td>
			</tr>
		</thead>
	</tbody>
	{% endfor%}
</table>
{% endblock %}