app/todo/models.py
from .. import db
from datetime import datetime
import enum

class Priority(enum.Enum):
    LOW = 1
    MEDIUM = 2
    HIGH = 3


class Progress(enum.Enum):
    TODO = 1
    DOING = 2
    DONE = 3

task_user = db.Table('task_user',
                     db.Column('user_id', db.Integer, db.ForeignKey('users.id')),
                     db.Column('task_id', db.Integer, db.ForeignKey('task.id'))
                     )

class Task(db.Model):
	__tablename__ = "task"

	id = db.Column(db.Integer, primary_key=True, autoincrement=True)
	title = db.Column(db.String(120), nullable=False)
	description = db.Column(db.String(2000), nullable=True)
	created = db.Column(db.DateTime, default=datetime.now())
	modified = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
	deadline = db.Column(db.DateTime)
	priority = db.Column(db.Enum(Priority, values_callable=lambda x: [str(member.value) for member in Priority]))
	progress = db.Column(db.Enum(Progress, values_callable=lambda x: [str(member.value) for member in Progress]))
	owner_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
	category_id = db.Column(db.Integer, db.ForeignKey('category.id'))

	users = db.relationship('User', secondary=task_user, backref=db.backref('tasks', lazy='dynamic'), lazy='dynamic')

	def __repr__(self):
	    return f"Title: {self.title}"
		
class Category(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False, unique=True)
    tasks = db.relationship('Task', backref='category', lazy='dynamic')

app/todo/__init__.py
from flask import Blueprint

todo_bp = Blueprint('todo', __name__, template_folder='templates/todo')
from . import views

app/todo/views.py
from flask import render_template, request, redirect, url_for, flash, current_app
from .. import db
from .models import Task, Category
from . import todo_bp
from flask_login import login_required, current_user
from .form import Taskform, CategoryForm

@todo_bp.route('/task', methods=['GET'])
@login_required
def tasks():

    tasks_ = Task.query.order_by(Task.priority.desc(),
                                 Task.deadline.asc()
                                 ).all()   
    return render_template('task.html', tasks=tasks_)

@todo_bp.route('/task/create', methods=['GET', 'POST'])
@login_required
def task_create():
    form = Taskform()

    if form.validate_on_submit():

        title = form.title.data
        description = form.description.data
        deadline = form.deadline.data
        priority = form.priority.data
        progress = form.progress.data
        category = form.category.data
        task_info = Task(title=title,
                         description=description,
                         deadline=deadline,
                         priority=priority,
                         progress=progress,
                         category_id=category,
                         owner_id=current_user.get_id())
        task_info.users.append(current_user)
        db.session.add(task_info)
        db.session.commit()

        flash(f"Task created!", category='success')
        return redirect(url_for("todo.task_create"))

    elif request.method == 'POST':
        flash("Validation failed!", category='warning')
        return redirect(url_for("todo.task_create"))
    
    return render_template('task_create.html', form=form)

@todo_bp.route('/task/<int:id>',methods=['GET', 'POST'])
@login_required
def task(id):
    task = Task.query.filter_by(id=id).first()
    task_detail = {
        'Title': task.title,
        'Description': task.description,
        'Created': task.created,
        'Modified': task.modified,
        'Deadline': task.deadline.date(),
        'Priority': task.priority,
        'Progress': task.progress
    }
    form = Taskform()

    return render_template('single_task.html', task_detail=task_detail,
                           id=task.id,
                           form=form,
                           assigned=task.users,
                           user=current_user)


@todo_bp.route('/task/<int:id>/update', methods=['GET', 'POST'])
@login_required
def task_update(id):
    
    form = Taskform()
    if form.validate_on_submit():
        title = form.title.data
        description = form.description.data
        deadline = form.deadline.data
        priority = form.priority.data
        progress = form.progress.data

        task = Task.query.filter_by(id=id).first()
        task.title = title
        task.description = description
        task.deadline = deadline
        task.priority = priority
        task.progress = progress
        db.session.add(task)
        db.session.commit()

        flash(f"Task successfully updated", category='success')
        return redirect(url_for("to_do.task", id=id))

    elif request.method == 'POST':
        print(form.errors, form.description.data)
        flash("Validation failed!", category='warning')
        return redirect(url_for("todo.task", id=id))

    return render_template('task_update.html', form=form, task_id=id)

@todo_bp.route('/task/<int:id>/delete', methods=['GET'])
@login_required
def task_delete(id):
    task_ = Task.query.get_or_404(id)
    
    try:
        db.session.delete(task_)
    except:
        db.session.rollback()
    else:
        db.session.commit()
        flash("Task deleted", category='success')
        current_app.logger.info("Task deleted")
    
    return redirect(url_for('to_do.task'))

@todo_bp.route('/categories', methods=['GET'])
@login_required
def categories():
    categories_ = Category.query.all()
    return render_template('categories.html', categories=categories_)


@todo_bp.route('/category/create', methods=['GET', 'POST'])
@login_required
def category_add():
    form = CategoryForm()
    
    if form.validate_on_submit():
        if current_user.is_authenticated:
            category = Category(name=form.name.data) 

            try:
                db.session.add(category)
            except:
                db.session.rollback()
            else:
                db.session.commit()
                flash("Category added", category='success')
        else:
            return redirect(url_for('account.login'))
  
    
    if request.method == 'POST':
        return redirect(url_for('todo.categories')) 
    
    return render_template('category_create.html', form=form)


@todo_bp.route('/category/<int:id>/update', methods=['GET', 'POST'])
@login_required
def category_update(id):
    category_ = Category.query.get_or_404(id)
    
    form = CategoryForm(name=category_.name)
    
    if form.validate_on_submit():
        if current_user.is_authenticated:
            try:
                category_.name = form.name.data
            except:
                db.session.rollback()
            else:
                db.session.commit()
                flash("Category updated", category='success')
                current_app.logger.info("Category updated")
        else:
            return redirect(url_for('account.login'))
  
    if request.method == 'POST':
        return redirect(url_for('to_do.categories', id=category_.id)) 
    
    return render_template('category_form.html', form=form)

@todo_bp.route('/categories/<int:id>/delete', methods=['GET'])
@login_required
def category_delete(id):
    category_ = Category.query.get_or_404(id)
    
    try:
        db.session.delete(category_)
    except:
        db.session.rollback()
    else:
        db.session.commit()
        flash("Category deleted", category='success')
        current_app.logger.info("Category deleted")
    
    return redirect(url_for('to_do.categories'))

app/todo/templates/todo/categories.html
{% extends 'layout.html' %}

{% block content %}

<table class="table table-bordered">
	<thead class="table-primary">
		<tr>
			<th scope="col">ID</th>
			<th scope="col">Name</th>
			<th scope="col">Buttons</th>
		</tr>
	</thead>
	<tbody>
		{% for category in categories %}
		<tr>
			<td>{{category.id}}</td>
			<td>{{category.name}}</td>
			<td>
				<a href="{{url_for('todo.category_delete', id=category.id)}}">
					<input type="button" class="btn btn-danger" value="Delete">
				</a>
				<a href="{{url_for('todo.category_update', id=category.id)}}">
					<input type="button" class="btn btn-primary" value="Edit">
				</a>
			</td>
		</tr>
	</tbody>
	{% endfor%}
</table>


{% endblock %}

app/todo/templates/todo/category_create.html
{% extends 'layout.html' %}

{% block content %}

{% from "_render_field.html" import render_field %}

<div class="col-6 mx-auto">

	<div class="card">

		<div class="card-header">
			<h5>Category</h5>
		</div>

		<div class="card-body">
			<form method="post">
				{{ form.csrf_token }}
				{{ render_field(form.name, class="form-control") }}
				{{ form.submit(class="btn btn-primary") }}
			</form>
		</div>

	</div>

</div>


{% endblock %}

app/todo/templates/todo/single_task.html
{% extends 'layout.html' %}

{% block content %}

<table class="table">
	<tbody>
		{% for label, text_data in task_detail.items() %}
		<tr>
			<td>{{ label }}</td>
			{% if label == "Priority" or label == "Progress" %}
			<td>{{ text_data.name }}</td>
			{% else %}
			<td>{{ text_data|safe }}</td>
			{% endif %}
		</tr>
		{% endfor %}
		<tr>
			<td>
				{% for user in assigned %}
				<div class="row">
					<div class="col-2">
						<a class="link-dark" href="{{ url_for('account.account', user_id=user.id) }}">{{
							user.username }}</a>
					</div>
					<div class="col-9"></div>
				</div>
				{% endfor %}
			</td>
		</tr>
		<tr>
			<td>
				<a class="btn btn-primary" href="{{ url_for('todo.task_update', id=id) }}">Update task</a>
			</td>
			<td>
				<a class="btn btn-danger" href="{{ url_for('todo.task_delete', id=id) }}">Delete task</a>
			</td>

		</tr>
	</tbody>
</table>

{% endblock %}

app/todo/templates/todo/task.html
{% extends 'layout.html' %}


{% block content %}

<table class="table table-hover table-bordered">
	<thead class="table-primary">
		<tr>
			<th scope="col">Title</th>
			<th scope="col">Description</th>
			<th scope="col">Category</th>
			<th scope="col">Priority</th>
			<th scope="col">Progress</th>
			<th scope="col">Deadline</th>
		</tr>
	</thead>
	<tbody>
		{% for task in tasks %}
		<tr>
			<td><a href="{{url_for('todo.task', id=task.id) }}">{{task.title}}</a></td>
			<td>{{task.description|safe}}</td>
			<td>{{task.category.name}}</td>
			<td>{{task.priority.name|capitalize }}</td>
			<td>{{task.progress.name|capitalize }}</td>
			<td>{{task.deadline}}</td>
		</tr>
	</tbody>
	{% endfor%}
</table>

{% endblock %}

app/todo/templates/todo/task_create.html
{% extends 'layout.html' %}

{% block content %}

{% from "_render_field.html" import render_field %}

<div class="col-6 mx-auto">

	<div class="card">

		<div class="card-header">
			<h5>Create task</h5>
		</div>
		<div class="card-body">
			<form action="{{url_for('todo.task_create')}}" method="post" class="">
				{{ form.hidden_tag() }}
				{% for field in form if field not in [form.submit, form.hidden_tag, form.csrf_token] %}
				{{render_field(field, class="form-control f-input")}}
				{% endfor %}
				{{ form.submit(class_="form-control btn btn-primary") }}
			</form>
		</div>

	</div>

</div>

{% endblock %}

app/todo/templates/todo/task_update.html
{% extends 'layout.html' %}
{% block content %}


{% from "_render_field.html" import render_field %}

<div class="col-6 mx-auto">

	<div class="card">

		<div class="card-header">
			<h5>Edit</h5>
		</div>
		<div class="card-body">
			<form action="{{ url_for('todo.task_update', id=task_id) }}" method="post" class="">
				{{ form.hidden_tag() }}
				{% for field in form if field not in [form.submit, form.hidden_tag, form.csrf_token] %}
				{{render_field(field, class="form-control f-input")}}
				{% endfor %}
				{{ form.submit(class_="form-control btn btn-primary") }}
			</form>
		</div>

	</div>

</div>

{% endblock %}

app/todo/templates/todo/user_tasks.html
{% extends 'layout.html' %}

{% block content %}
<h2>Tasks</h2>
<table class="table table-bordered">
	<thead class="table-primary">
		<tr>
			<th scope="col">Title</th>
			<th scope="col">Deadline</th>
			<th scope="col">Priority</th>
			<th scope="col">Progress</th>
			<th scope="col">Owner</th>
			<th scope="col">Assigned</th>
		</tr>
	</thead>
	<tbody>
		{% for task in task_list %}
		<tr>
			<td><a href="{{ url_for('todo.task', id=task.id) }}">{{ task.title }}</a></td>
			<td>{{ task.deadline }}</td>
			<td>{{ task.priority.name }}</td>
			<td>{{ task.progress.name }}</td>
			<td><a href="{{ url_for('todo.user_profile', user_id=task.owner_id) }}">{{ task.owner.username }}</a></td>
			<td>
				{% for user in task.users %}
				<p><a href="{{ url_for('todo.user_profile', user_id=user.id) }}">{{ user.username }}</a></p>
				{% endfor %}
			</td>
		</tr>
	</tbody>
	{% endfor%}
</table>

{% endblock %}